(define (make-account balance password)
  (let ((fail-count 0))
  	(define (withdraw amount)
		(if (>= balance amount)
			(begin (set! balance (- balance amount))
				   balance)
			"Insufficient funds"))
 	 (define (deposit amount)
		(set! balance (+ balance amount))
		balance)
 	 (define (dispatch p m)
		(cond ((not (eq? password p))
			   (begin (set! fail-count (+ fail-count 1))
					  (if (= fail-count 7)
						(lambda (x) "call-the-cops")
						(lambda (x) "Incorrect password"))))
			  ((eq? m 'withdraw)
			   (begin (set! fail-count 0)
					  withdraw))
			  ((eq? m 'deposit)
			   (begin (set! fail-count 0)
					  deposit))
			  (else (error "Unknown request: MAKE-ACCOUNT" m))))
	 dispatch))

(define acc (make-account 100 'secret-password))

((acc 'secret-password 'withdraw) 40)
((acc 'some-other-password 'deposit) 50)
