(define (make-monitored f)
  (let ((count 0))
    (define (how-many-calls?)
      count)
    (define (reset-count)
      (begin (set! count 0)
             count))
    (define (mf v)
      (cond ((eq? v 'how-many-calls?) (how-many-calls?))
            ((eq? v 'reset-count) (reset-count))
            (else (begin (set! count (+ count 1)) (f v)))))
    mf))
